<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eylul">

<title>PBMC scRNA-seq Analysis Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
  
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PBMC scRNA-seq Analysis Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eylul </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"pbmc_filtered.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>markers <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">CD4_T =</span> <span class="fu">c</span>(<span class="st">"CD3D"</span>, <span class="st">"CD3E"</span>, <span class="st">"CD4"</span>, <span class="st">"IL7R"</span>, <span class="st">"CCR7"</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">CD8_T =</span> <span class="fu">c</span>(<span class="st">"CD3D"</span>, <span class="st">"CD3E"</span>, <span class="st">"CD8A"</span>, <span class="st">"CD8B"</span>, <span class="st">"GZMK"</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">NK =</span> <span class="fu">c</span>(<span class="st">"NKG7"</span>, <span class="st">"GNLY"</span>, <span class="st">"KLRD1"</span>, <span class="st">"PRF1"</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">B =</span> <span class="fu">c</span>(<span class="st">"MS4A1"</span>, <span class="st">"CD79A"</span>, <span class="st">"CD79B"</span>, <span class="st">"BANK1"</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Plasma =</span> <span class="fu">c</span>(<span class="st">"MZB1"</span>, <span class="st">"JCHAIN"</span>, <span class="st">"IGHG1"</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">CD14_Monocyte =</span> <span class="fu">c</span>(<span class="st">"LYZ"</span>, <span class="st">"LST1"</span>, <span class="st">"S100A8"</span>, <span class="st">"S100A9"</span>),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">FCGR3A_Monocyte =</span> <span class="fu">c</span>(<span class="st">"FCGR3A"</span>, <span class="st">"MS4A7"</span>, <span class="st">"LST1"</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">DC =</span> <span class="fu">c</span>(<span class="st">"FCER1A"</span>, <span class="st">"CST3"</span>, <span class="st">"CLEC10A"</span>),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">pDC =</span> <span class="fu">c</span>(<span class="st">"GZMB"</span>, <span class="st">"IRF7"</span>, <span class="st">"TCF4"</span>, <span class="st">"IL3RA"</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Platelet =</span> <span class="fu">c</span>(<span class="st">"PDBP"</span>, <span class="st">"PF4"</span>, <span class="st">"GP9"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>## Introduction and Biological Background</p>
<p>Peripheral Blood Mononuclear Cells (PBMCs) are critical components of the human immune system, characterized by a round, single-lobed nucleus. The circulates in the peripheral bloodstream and comprise heterogeneous mixture of immune cells that play vital roles in adaptive and innate immunity:</p>
<p><strong>* **T Lymphocytes (T cells):</strong>** Central to cell-mediated immunity, comprising major subsets such as CD4 T helper cells (expressing *<em>CD3D</em>*, *<em>CD3E</em>*, *<em>CD4</em>*, *<em>IL7R</em>*, *<em>CCR7</em>*) which coordinate immune responses, and CD8 + Cytotoxic T cells (expressing *<em>CD8A</em>*, *<em>CD8B</em>*, *<em>GZMK</em>*) which target infected or malignent cells.</p>
<p><strong>* **B Lymphocytes (B cells):</strong>** Responsible for humoral immunity and antibody production, identified by markers like *<em>MS4A1</em>* (CD20), *<em>CD79A</em>*, and *<em>CD79B</em>*, alongside differentiated antibody-secreting Plasma cells (*<em>MZB1</em>*, *<em>JCHAIN</em>*).</p>
<p><strong>* **Natural Killer (NK) Cells:</strong>** Innate lymphoid cells providing rapid responses against viral infections and tumors, characterized by high expression of *<em>NKG7</em>*, *<em>GNLY</em>*, *<em>KLRD1</em>*, and *<em>PRF1</em>*.</p>
<p><strong>* **Monocytes:</strong>** Innate immune cells involved in phagocytosis and immune regulation, divided into classical CD14 + Monocytes (*<em>LYZ</em>*, *<em>S100A8</em>*, *<em>S100A9</em>*) and non-classical FCGR3A + Monocytes (*<em>FGCR3A</em>*, *<em>MS4A7</em>*).</p>
<p>* **<strong>Dendritic Cells (DCs &amp; pDCs):</strong>** Professional antigen-presenting cells bridging innate and adaptive immunity, marked by *<em>FCER1A</em>*, *<em>CST3</em>* (conventional DCs) and *<em>IRF7</em>*, *<em>IL3RA</em>* (plasmacytoid DCs).</p>
<p>## Dataset Description</p>
<p>This project utilizes a multi-sample single-cell RNA sequencing (scRNA-seq) dataset consisting of approxmately 20,000 human PBMCs obtained from 10x Genomics, representing four distinct healthy donors (Donors 1-4). This multiplexed experimental design allows us to evaluate inter-sample heterogeneity, verify technical reproducibility, and robustly characterize major immune cell populations at single-cell resolution.</p>
<pre><code></code></pre>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cluster_markers <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"cluster_markers.rds"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cluster_markers, <span class="at">n =</span> <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       p_val avg_log2FC pct.1 pct.2 p_val_adj cluster   gene
IL7R       0  1.8603833 0.979 0.391         0       0   IL7R
CD28       0  1.8235943 0.855 0.274         0       0   CD28
TRAC       0  2.0828789 0.826 0.256         0       0   TRAC
CD2        0  1.8677242 0.948 0.385         0       0    CD2
CAMK4      0  1.0108154 0.958 0.397         0       0  CAMK4
TRAT1      0  1.9388516 0.808 0.254         0       0  TRAT1
CD3E       0  1.3464066 0.928 0.375         0       0   CD3E
CD3D       0  1.4558698 0.857 0.305         0       0   CD3D
IL32       0  1.5883531 0.878 0.354         0       0   IL32
BCL11B     0  0.8851514 0.976 0.456         0       0 BCL11B
ITM2A      0  1.9093087 0.784 0.274         0       0  ITM2A
CD5        0  1.7708486 0.784 0.284         0       0    CD5
INPP4B     0  1.0738608 0.775 0.281         0       0 INPP4B
ICOS       0  1.9873027 0.689 0.205         0       0   ICOS
LTB        0  1.7789170 0.964 0.482         0       0    LTB</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cell_type_names <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"0"</span> <span class="ot">=</span> <span class="st">"CD4+ T cells"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"CD8+ T cells"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"B cells"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"4"</span> <span class="ot">=</span> <span class="st">"NK cells"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"5"</span> <span class="ot">=</span> <span class="st">"Dendritic cells"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"6"</span> <span class="ot">=</span> <span class="st">"Platelets"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"7"</span> <span class="ot">=</span> <span class="st">"Memory CD4 T"</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"8"</span> <span class="ot">=</span> <span class="st">"B cells"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"9"</span> <span class="ot">=</span> <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"10"</span> <span class="ot">=</span> <span class="st">"NK cells"</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"11"</span> <span class="ot">=</span> <span class="st">"DC"</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"12"</span> <span class="ot">=</span> <span class="st">"Platelets"</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"13"</span> <span class="ot">=</span> <span class="st">"T cells"</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"14"</span> <span class="ot">=</span> <span class="st">"B cells"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"15"</span> <span class="ot">=</span> <span class="st">"Monocytes"</span>,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"16"</span> <span class="ot">=</span> <span class="st">"Other"</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>marker_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">Gene =</span> cluster_markers<span class="sc">$</span>gene,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">CellType =</span> cell_type_names[<span class="fu">as.character</span>(cluster_markers<span class="sc">$</span>cluster)]</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(marker_df, <span class="st">"data/merker_genes_pbmc.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>## Day 3: Quality Control (QC)</p>
<p>To ensure high-quality data for downstream analysis, we perform quality control filtering on the single-cell RNA sequencing data. This includes calculating mitochondrial gene percentages (“percent.mt”) to filter out dying or damaged cells, as well as examining gene and UMI counts (“nFeature_RNA” and “nCount_RNA”).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>h5_files <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="st">"data"</span>, <span class="at">pattern =</span> <span class="st">".h5$"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>counts_donor1 <span class="ot">&lt;-</span> <span class="fu">Read10X_h5</span>(h5_files[<span class="dv">1</span>])</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>donor1 <span class="ot">&lt;-</span> <span class="fu">CreateSeuratObject</span>(<span class="at">counts =</span> counts_donor1, <span class="at">project =</span> <span class="st">"Donor1"</span>, <span class="at">min.cells =</span> <span class="dv">3</span>, <span class="at">min.features =</span> <span class="dv">200</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>donor1[[<span class="st">"percent.mt"</span>]] <span class="ot">&lt;-</span> <span class="fu">PercentageFeatureSet</span>(donor1, <span class="at">pattern =</span> <span class="st">"^MT-"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>donor1<span class="sc">$</span>donor <span class="ot">&lt;-</span> <span class="st">"Donor1"</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>donor1<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="st">"Female"</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>donor1<span class="sc">$</span>age_group <span class="ot">&lt;-</span> <span class="st">"Adult"</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(donor1<span class="sc">@</span>meta.data, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   orig.ident nCount_RNA nFeature_RNA percent.mt  donor    sex
AAACCAAAGGTGACGA-1     Donor1      42833         7079   3.417925 Donor1 Female
AAACCCTGTGACGAGT-1     Donor1       4890         2102   3.619632 Donor1 Female
AAACGAATCAGGCTAC-1     Donor1      12498         3564   3.768603 Donor1 Female
AAACGACAGATTGACT-1     Donor1      22193         4366   3.127112 Donor1 Female
AAACGATGTCTTGAAC-1     Donor1      10305         2945   3.114993 Donor1 Female
                   age_group
AAACCAAAGGTGACGA-1     Adult
AAACCCTGTGACGAGT-1     Adult
AAACGAATCAGGCTAC-1     Adult
AAACGACAGATTGACT-1     Adult
AAACGATGTCTTGAAC-1     Adult</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>counts_donor2 <span class="ot">&lt;-</span> <span class="fu">Read10X_h5</span>(h5_files[<span class="dv">2</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>donor2 <span class="ot">&lt;-</span> <span class="fu">CreateSeuratObject</span>(<span class="at">counts =</span> counts_donor2, <span class="at">project =</span> <span class="st">"Donor2"</span>, <span class="at">min.cells =</span> <span class="dv">3</span>, <span class="at">min.features =</span> <span class="dv">200</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>donor2[[<span class="st">"percent.mt"</span>]] <span class="ot">&lt;-</span> <span class="fu">PercentageFeatureSet</span>(donor2, <span class="at">pattern =</span> <span class="st">"^MT-"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>donor2<span class="sc">$</span>donor <span class="ot">&lt;-</span> <span class="st">"Donor2"</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>donor2<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="st">"Female"</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>donor2<span class="sc">$</span>age_group <span class="ot">&lt;-</span> <span class="st">"Adult"</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(donor2<span class="sc">@</span>meta.data, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   orig.ident nCount_RNA nFeature_RNA percent.mt  donor    sex
AAACCAAAGCCTTGGG-1     Donor2      21321         4526   2.012101 Donor2 Female
AAACCAAAGGTATGGG-1     Donor2      20350         4712   1.110565 Donor2 Female
AAACCAAAGTAGCCGT-1     Donor2       9428         3273   2.068307 Donor2 Female
AAACCAAAGTTACGAT-1     Donor2       5511         1946   4.427509 Donor2 Female
AAACCCGCAAATCAGC-1     Donor2      22002         4321   2.199800 Donor2 Female
                   age_group
AAACCAAAGCCTTGGG-1     Adult
AAACCAAAGGTATGGG-1     Adult
AAACCAAAGTAGCCGT-1     Adult
AAACCAAAGTTACGAT-1     Adult
AAACCCGCAAATCAGC-1     Adult</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>counts_donor3 <span class="ot">&lt;-</span> <span class="fu">Read10X_h5</span>(h5_files[<span class="dv">3</span>])</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>donor3 <span class="ot">&lt;-</span> <span class="fu">CreateSeuratObject</span>(<span class="at">counts =</span> counts_donor3, <span class="at">project =</span> <span class="st">"Donor3"</span>, <span class="at">min.cells =</span> <span class="dv">3</span>, <span class="at">min.features =</span> <span class="dv">200</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>donor3[[<span class="st">"percent.mt"</span>]] <span class="ot">&lt;-</span> <span class="fu">PercentageFeatureSet</span>(donor3, <span class="at">pattern =</span> <span class="st">"^MT-"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>donor3<span class="sc">$</span>donor <span class="ot">&lt;-</span> <span class="st">"Donor3"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>donor3<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="st">"Male"</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>donor3<span class="sc">$</span>age_group <span class="ot">&lt;-</span> <span class="st">"Adult"</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(donor3<span class="sc">@</span>meta.data, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   orig.ident nCount_RNA nFeature_RNA percent.mt  donor  sex
AAACCAAAGCGCCTTC-1     Donor3      16487         3675   2.693031 Donor3 Male
AAACCAAAGTTAATGC-1     Donor3      11352         3130   2.017266 Donor3 Male
AAACCATTCCGCGACA-1     Donor3      15389         3341   2.456300 Donor3 Male
AAACCATTCGTTCGTT-1     Donor3       3782         1615   8.646219 Donor3 Male
AAACCCGCACATAGCG-1     Donor3      11328         3184   1.765537 Donor3 Male
                   age_group
AAACCAAAGCGCCTTC-1     Adult
AAACCAAAGTTAATGC-1     Adult
AAACCATTCCGCGACA-1     Adult
AAACCATTCGTTCGTT-1     Adult
AAACCCGCACATAGCG-1     Adult</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>counts_donor4 <span class="ot">&lt;-</span> <span class="fu">Read10X_h5</span>(h5_files[<span class="dv">4</span>])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>donor4 <span class="ot">&lt;-</span> <span class="fu">CreateSeuratObject</span>(<span class="at">counts =</span> counts_donor4, <span class="at">project =</span> <span class="st">"Donor4"</span>, <span class="at">min.cells =</span> <span class="dv">3</span>, <span class="at">min.features =</span> <span class="dv">200</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>donor4[[<span class="st">"percent.mt"</span>]] <span class="ot">&lt;-</span> <span class="fu">PercentageFeatureSet</span>(donor4, <span class="at">pattern =</span> <span class="st">"^MT-"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>donor4<span class="sc">$</span>donor <span class="ot">&lt;-</span> <span class="st">"Donor4"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>donor4<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="st">"Male"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>donor4<span class="sc">$</span>age_group <span class="ot">&lt;-</span> <span class="st">"Adult"</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(donor4<span class="sc">@</span>meta.data, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   orig.ident nCount_RNA nFeature_RNA percent.mt  donor  sex
AAACCAAAGGCGCTTG-1     Donor4      10084         2847   9.044030 Donor4 Male
AAACCAAAGTAGGACG-1     Donor4       9336         3108   3.309769 Donor4 Male
AAACCATTCCAGCTAA-1     Donor4       7089         2751   3.879250 Donor4 Male
AAACCATTCCATCCGC-1     Donor4       6664         2421   6.692677 Donor4 Male
AAACCATTCGACCAGT-1     Donor4      11082         3244   2.752211 Donor4 Male
                   age_group
AAACCAAAGGCGCTTG-1     Adult
AAACCAAAGTAGGACG-1     Adult
AAACCATTCCAGCTAA-1     Adult
AAACCATTCCATCCGC-1     Adult
AAACCATTCGACCAGT-1     Adult</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">merge</span>(donor1, <span class="at">y =</span> <span class="fu">c</span>(donor2, donor3, donor4),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">add.cell.ids =</span> <span class="fu">c</span>(<span class="st">"D1"</span>, <span class="st">"D2"</span>, <span class="st">"D3"</span>, <span class="st">"D4"</span>),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">project =</span> <span class="st">"PBMC_QC"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">subset</span>(pbmc_filtered, <span class="at">subset =</span> nFeature_RNA <span class="sc">&gt;</span> <span class="dv">200</span> <span class="sc">&amp;</span> nFeature_RNA <span class="sc">&lt;</span> <span class="dv">4000</span> <span class="sc">&amp;</span> percent.mt <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">NormalizeData</span>(pbmc_filtered)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">FindVariableFeatures</span>(pbmc_filtered)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">ScaleData</span>(pbmc_filtered)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">RunPCA</span>(pbmc_filtered)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">IntegrateLayers</span>(</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">object =</span> pbmc_filtered,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> RPCAIntegration,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">new.reduction =</span> <span class="st">"integrated.dr"</span>,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="cn">FALSE</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">FindNeighbors</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"integrated.dr"</span>, <span class="at">dims =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>)</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">FindClusters</span>(pbmc_filtered, <span class="at">resolution =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 14952
Number of edges: 600416

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.9244
Number of communities: 18
Elapsed time: 1 seconds</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">RunUMAP</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"integrated.dr"</span>, <span class="at">dims =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">group.by =</span> <span class="st">"seurat_clusters"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"UMAP - Integrated Clusters"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">group.by =</span> <span class="st">"orig.ident"</span>) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"UMAP - Integrated by Donor"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Idents</span>(pbmc_filtered) <span class="ot">&lt;-</span> pbmc_filtered<span class="sc">$</span>seurat_clusters</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>new.cluster.ids <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"0"</span> <span class="ot">=</span> <span class="st">"CD4+ T cells"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"CD8+ T cells"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"B cells"</span>, <span class="st">"4"</span> <span class="ot">=</span> <span class="st">"NK cells"</span>, <span class="st">"5"</span> <span class="ot">=</span> <span class="st">"Dendritic cells"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"6"</span> <span class="ot">=</span> <span class="st">"Platelets"</span>, <span class="st">"7"</span> <span class="ot">=</span> <span class="st">"Memory CD4 T"</span>, <span class="st">"8"</span> <span class="ot">=</span> <span class="st">"B cells"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"9"</span> <span class="ot">=</span> <span class="st">"CD14+ Monocytes"</span>, <span class="st">"10"</span> <span class="ot">=</span> <span class="st">"NK cells"</span>, <span class="st">"11"</span> <span class="ot">=</span> <span class="st">"DC"</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"12"</span> <span class="ot">=</span> <span class="st">"Platelets"</span>, <span class="st">"13"</span> <span class="ot">=</span> <span class="st">"T cells"</span>,  <span class="st">"14"</span> <span class="ot">=</span> <span class="st">"B cells"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"15"</span> <span class="ot">=</span> <span class="st">"Monocytes"</span>, <span class="st">"16"</span> <span class="ot">=</span> <span class="st">"other"</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">RenameIdents</span>(pbmc_filtered, new.cluster.ids)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>pbmc_filtered<span class="sc">$</span>celltype <span class="ot">&lt;-</span> <span class="fu">Idents</span>(pbmc_filtered)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">DimPlot</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">label =</span> <span class="cn">FALSE</span>, <span class="at">pt.size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Annotated PBMC Cell Types"</span>)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">FeatureScatter</span>(pbmc_filtered, <span class="at">feature1 =</span> <span class="st">"nCount_RNA"</span>, <span class="at">feature2 =</span> <span class="st">"nFeature_RNA"</span>, <span class="at">group.by =</span> <span class="st">"donor"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">FeatureScatter</span>(pbmc_filtered, <span class="at">feature1 =</span> <span class="st">"nCount_RNA"</span>, <span class="at">feature2 =</span> <span class="st">"percent.mt"</span>, <span class="at">group.by =</span> <span class="st">"donor"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>plot1 <span class="sc">+</span> plot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">subset</span>(pbmc_filtered,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">subset =</span> nFeature_RNA <span class="sc">&gt;</span> <span class="dv">200</span> <span class="sc">&amp;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                          nFeature_RNA <span class="sc">&lt;</span> <span class="dv">6000</span> <span class="sc">&amp;</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                          percent.mt <span class="sc">&lt;</span> <span class="dv">15</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>pbmc_filtered</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>An object of class Seurat 
27385 features across 14952 samples within 1 assay 
Active assay: RNA (27385 features, 2000 variable features)
 9 layers present: counts.Donor1, counts.Donor2, counts.Donor3, counts.Donor4, data.Donor1, data.Donor2, data.Donor3, data.Donor4, scale.data
 3 dimensional reductions calculated: pca, integrated.dr, umap</code></pre>
</div>
</div>
<p>Quality Control (QC) and Filtering</p>
<p>To ensure high data quality for downstream analysis, low-quality cells, empty droplets, and potential doublets were filtered out based on quality control metrics.</p>
<p>QC Metrics Visualization</p>
<p>We generated violin plots and scatter plots for nFeature_RNA , nCount_RNA, and percent.mt across all four donors to assess data distribution.</p>
<p># Violin Plots</p>
<p>VlnPlot(pbmc_combined, feature = c(“nFeature_RNA”, “nCount_RNA”, “percent.mt”), ncol = 3, group.by = “donor”)</p>
<p>Filtering Tresholds and Decision</p>
<p>Based on standard single-cell RNA sequencing guidlines, we applied the following filtering criteria:</p>
<p>nFeature_RNA &gt; 200: Removes empty droplets or very low-quality cells.</p>
<p>nFeature_RNA &lt; 6000: Removes potential multi-cell doublets.</p>
<p>percent.mt &lt; 15: Removes damaged or dying cells with high mitochondrial RNA content.</p>
<p># Filtering</p>
<p>pbmc_filtered &lt;- subset(pbmc_combined,</p>
<p>subset = nFeature_RNA &gt; 200 &amp;</p>
<p>nFeature_RNA &lt; 6000 &amp;</p>
<p>percent.mt &lt; 15)</p>
<p>pbmc_filtered</p>
<p>After filtering, 21,586 high-quality cells across 27,385 features were retained for further analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">NormalizeData</span>(pbmc_filtered, <span class="at">normalization.method =</span> <span class="st">"LogNormalize"</span>, <span class="at">scale.factor =</span> <span class="dv">10000</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">FindVariableFeatures</span>(pbmc_filtered, <span class="at">selection.method =</span> <span class="st">"vst"</span>, <span class="at">nfeatures =</span> <span class="dv">2000</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">ScaleData</span>(pbmc_filtered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Normalization and Dimensionality Reduction</p>
<p>To prepare the filtered gene expression matrix for downstream clustering and visualization, we performed data normalization, identified highly variable genes, scaled the data, and ran linear and non-linear dimensionality reduction.</p>
<ol type="1">
<li>Normalization and Variable Feature Selection</li>
</ol>
<p>First, we applied a global-scaling normalization method (“LogNormalize”) that normalizes the gene expression measurements for each cell by the total expression, multiplies this by a scale factor (10,000), and log-transforms the result. Then, we identified the top 2,000 highly variable features (genes) that drive biological heterogeneity across cells.</p>
<p>pbmc_filtered &lt;- NormalizeData(pbmc_filtered, normalization.method = “LogNormalize”, scale.factor = 10000)</p>
<p>pbmc_filtered &lt;- FindVariableFeatures(pbmc_filtered, selection.method = “vst”, nfeatures = 2000)</p>
<p>pbmc_filtered &lt;- ScaleData(pbmc_filtered)</p>
<ol start="2" type="1">
<li>PCA and UMAP Dimensionality Reduction</li>
</ol>
<p>We ran Principal Component Analysis (PCA) on the scaled variable features to reduce the dimensionality of the dataset. Based on the PCA and Elbow plot evaluation, we selected the top 15 principal components (dims = 1:15) to run UMAP for 2D visualization.</p>
<p>pbmc_filtered &lt;- RunPCA(pbmc_filtered, features = VariableFeatures(object = pbmc_filtered))</p>
<p>pbmc_filtered &lt;- RunUMAP(pbmc_filtered, dims = 1:15)</p>
<p>DimPlot(pbmc_filtered, reduction = “umap”, group.by = “donor”)</p>
<p>UMAP Interpretation</p>
<p>The UMAP plot colored by donor shows a well-integrated distribution across all four donors (Donor1, Donor2, Donor3, Donor4). The homogeneous mixing within the distinct cellular islands indicates that technical batch effects are minimal, and the clusters accurately reflect underlying biological cell populations.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">FindNeighbors</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"integrated.dr"</span>, <span class="at">dims =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">FindClusters</span>(pbmc_filtered, <span class="at">resolution =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.4</span>, <span class="fl">0.6</span>, <span class="fl">0.8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 14952
Number of edges: 540077

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.9554
Number of communities: 11
Elapsed time: 1 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 14952
Number of edges: 540077

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.9324
Number of communities: 15
Elapsed time: 1 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 14952
Number of edges: 540077

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.9139
Number of communities: 16
Elapsed time: 1 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 14952
Number of edges: 540077

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.8979
Number of communities: 21
Elapsed time: 1 seconds</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">DimPlot</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">group.by =</span> <span class="st">"RNA_snn_res.0.4"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Resolution 0.4"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">DimPlot</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">group.by =</span> <span class="st">"RNA_snn_res.0.6"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Resolution 0.6"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Idents</span>(pbmc_filtered) <span class="ot">&lt;-</span> <span class="st">"RNA_snn_res.0.4"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">pt.size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"PBMC Clusters (Resolution 0.4)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>## Clustering Interpretation</p>
<p>Following neighborhood graph construction and resolution testing, **<strong>resolution 0.4</strong>** was selected as the optimal parameter for downstream anlyses, yielding 17 distinct clusters. The UMAP visualization demonstrates clear, well- separated biological clusters corresponding to major PBMC populations (such as T cell subsets, monocytes, and other mononuclear cells) without introducing artificial over-clustering. This robust partitioning serves as the foundation for subsequent marker gene identification.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a> <span class="co">#| cache: true</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a> <span class="cf">if</span> (<span class="fu">file.exists</span>(<span class="st">"pbmc_markers.csv"</span>)) {</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>   pbmc_markers <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"pbmc_markers.csv"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a> } <span class="cf">else</span> {</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>   pbmc_markers <span class="ot">&lt;-</span> <span class="fu">FindAllMarkers</span>(pbmc_filtered,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">omly.pos =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">min.pct =</span> <span class="fl">0.25</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">logfc.treshold =</span> <span class="fl">0.25</span>)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>   <span class="fu">write.csv</span>(pbmc_markers, <span class="st">"pbmc_markers.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a> }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(pbmc_markers, <span class="at">file =</span> <span class="st">"cluster_markers.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>top10_markers <span class="ot">&lt;-</span> pbmc_markers <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(cluster) <span class="sc">%&gt;%</span> <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">wt =</span> avg_log2FC)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(top10_markers, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 7
# Groups:   cluster [1]
   p_val avg_log2FC pct.1 pct.2 p_val_adj cluster    gene   
   &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;  
 1     0       2.08 0.826 0.256         0 CD T cells TRAC   
 2     0       1.94 0.808 0.254         0 CD T cells TRAT1  
 3     0       1.99 0.689 0.205         0 CD T cells ICOS   
 4     0       1.93 0.705 0.245         0 CD T cells GATA3  
 5     0       4.26 0.47  0.032         0 CD T cells CCR4   
 6     0       2.52 0.392 0.066         0 CD T cells CD40LG 
 7     0       2.26 0.388 0.097         0 CD T cells CCR6   
 8     0       1.92 0.324 0.067         0 CD T cells IL2RA  
 9     0       1.96 0.3   0.067         0 CD T cells AQP3   
10     0       2.56 0.269 0.043         0 CD T cells TNFRSF4</code></pre>
</div>
</div>
<p>## Marker Gene Analysis</p>
<p>By employing the FindAllMarkers() function with standard stringency parameters (only.pos = TRUE, min.pct = 0.25, logfc.treshold = 0.25), robust signature genes were successfully extracted for all 17 biological clusters. The resulting marker table was exported as cluster_markers.csv for documentation, allowing downstream inspection of top-expressed genes (such as IL7R, CD3D, CD14, and MS4A1) to accurately map and annotate major PBMC cell types.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>canonical_markers <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"IL7R"</span>, <span class="st">"CD3D"</span>, <span class="st">"CD14"</span>, <span class="st">"LYZ"</span>, <span class="st">"MS4A1"</span>, <span class="st">"NKG7"</span>, <span class="st">"GNLY"</span>, <span class="st">"PPBP"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">DotPlot</span>(pbmc_filtered, <span class="at">features =</span> canonical_markers) <span class="sc">+</span> <span class="fu">RotatedAxis</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>new.cluster.ids <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD T cells"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD4 T cells"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD4 T cells"</span>,</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"B cells"</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"NK cells"</span>,</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD4 T cells"</span>,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD4 T cells"</span>,</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD4 T cells"</span>,</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD4 T cells"</span>,</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CD14+ Monocytes"</span>,</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Dendritic cells"</span>,</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Platelets"</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(new.cluster.ids) <span class="ot">&lt;-</span> <span class="fu">levels</span>(pbmc_filtered)</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>pbmc_filtered <span class="ot">&lt;-</span> <span class="fu">RenameIdents</span>(pbmc_filtered, new.cluster.ids)</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>pbmc_filtered<span class="sc">$</span>celltype <span class="ot">&lt;-</span> <span class="fu">Idents</span>(pbmc_filtered)</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(pbmc_filtered, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">pt.size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">NoLegend</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>## Cell Type Annotation</p>
<p>By cross-referencing cluster markers with well-established PBMC canonical genes (such as IL7R and CD3D for T cells, CD14 and LYZ for monocytes, MS4A1 for B cells, and NKG7 for NK cells), numerical clusters were successfully mapped to distinct biological populations. Using the RenameIdents() function, these labels were integrated into the Seurat object and visualized on the annotated UMAP map. This final cell type assignment confirms robust partitioning of major immune cell lineages, providing a solid foundation for subsequent donor comparison analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>cell_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(pbmc_filtered<span class="sc">$</span>orig.ident, pbmc_filtered<span class="sc">$</span>celltype)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cell_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        
         CD T cells CD4 T cells CD14+ Monocytes B cells NK cells
  Donor1        737        1584            1337     164      338
  Donor2        286        1715             920     435      434
  Donor3        557        1300            1525     128      153
  Donor4        436         954            1186     545      218</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>cell_proportions <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(cell_counts, <span class="at">margin =</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>cell_proportions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        
         CD T cells CD4 T cells CD14+ Monocytes   B cells  NK cells
  Donor1  17.716346   38.076923       32.139423  3.942308  8.125000
  Donor2   7.546174   45.250660       24.274406 11.477573 11.451187
  Donor3  15.206115   35.490035       41.632542  3.494403  4.176904
  Donor4  13.057802   28.571429       35.519617 16.322252  6.528901</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pbmc_filtered<span class="sc">@</span>meta.data, <span class="fu">aes</span>(<span class="at">x =</span> orig.ident, <span class="at">fill =</span> <span class="fu">Idents</span>(pbmc_filtered))) <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cell Type Proportions per Donor"</span>, <span class="at">x =</span> <span class="st">"Donor"</span>, <span class="at">y =</span> <span class="st">"Proportion"</span>, <span class="at">fill =</span> <span class="st">"Cell Type"</span>) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>## Donor Comparison Interpretation</p>
<p>To asses potential biological variations and sample-specific shifts across different individuals, cell type proportions were calculated for each donor. The stacked bar plot illustrates the relative abundance of each annotated cell population within **<strong>Donor1, Donor2, Donor3, and Donor4</strong>**. While core immune populations (such as T cells and monocytes) are consistently represented across all samples, subtle variations in cell type frequencies are observable between certain donors (e.g., Donor 2). These variations reflect natural inter-individual biological differences or potential technical variations, establishing a baseline for downstream comparative analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/Users/eylulimal/Desktop/PBMC_project"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>data_dir <span class="ot">&lt;-</span> <span class="st">"data/filtered_gene_bc_matrices/hg19/"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>candidate_genes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"XIST"</span>, <span class="st">"RPS4Y1"</span>, <span class="st">"EIF1AX"</span>, <span class="st">"CD40LG"</span>, <span class="st">"B2M"</span>, <span class="st">"S100A8"</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>existing_genes <span class="ot">&lt;-</span> candidate_genes[candidate_genes <span class="sc">%in%</span> <span class="fu">rownames</span>(pbmc_filtered)]</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>existing_genes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "XIST"   "RPS4Y1" "EIF1AX" "CD40LG" "B2M"    "S100A8"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">FeaturePlot</span>(pbmc_filtered, <span class="at">features =</span> existing_genes, <span class="at">pt.size =</span> <span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>##Interpretation Paragraph</p>
<p>Based on the candidate gene feature plots, key markers such as XIST, RPS4Y1, B2M, and S100A8 show robust detection across distinct cell populations. Specifically, sex-associated markers successfully differentiate cell distributions, while inflammatory and age-associated markers (e.g., S100A8 in monocytes) highlight active immune states. However, while we can observe these expression patterns across individual clusters and donors, we cannot definitively attribute these variations purely to systemic sex or age differences due to the limited cohort size and lack of biological replication per demographic group.</p>
<p>## Reasoning Prompt</p>
<p>The current dataset design does not allow us to cleanly separate sex effects, age effects, donor-specific biological effects, and technical batch effects. This is because biological variables are inherently confounded with donor identities in this small cohort (e.g., specific donors represent specific age and sex brackets.) To resolve this limitation and answer these biological questions convincingly, a more rigorous, expanded study design would be required-specifically incorporating a balanced multi-donor cohort with multiple individuals per age group for both biological sexes, alongside standardized technical processing.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>sex_age_candidate_genes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Gene_Symbol =</span> <span class="fu">c</span>(<span class="st">"XIST"</span>, <span class="st">"RPS4Y1"</span>, <span class="st">"EIF1AX"</span>, <span class="st">"CD40LG"</span>, <span class="st">"B2M"</span>, <span class="st">"S100A8"</span>),</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Category =</span> <span class="fu">c</span>(<span class="st">"Sex Chromosome Expression"</span>, <span class="st">"Sex Chromosome Expression"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"X-linked Immune Relevance"</span>, <span class="st">"X-linked Immune Relevance"</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Age-associated Marker"</span>, <span class="st">"Age-associated marker"</span>),</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Relevance =</span> <span class="fu">c</span>(</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Inactivates X chromosome in females; primary biological sex marker."</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Ribosomal protein on Y chromosome; standard male cell marker."</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"X-linked gene escaping inactivation; regulates immune cells."</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Critical for T-B cell interaction and adaptive immunity."</span>,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Upregulated in older cells due to inflammaging."</span>,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Associated with inflammaging and increased monocyte activation."</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">Location =</span> <span class="fu">c</span>(<span class="st">"X-linked"</span>, <span class="st">"Y-linked"</span>, <span class="st">"X-linked"</span>, <span class="st">"X-linked"</span>, <span class="st">"Autosomal"</span>, <span class="st">"Autosomal"</span>),</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">Source =</span> <span class="fu">c</span>(<span class="st">"ensembl/Literature"</span>, <span class="st">"Ensembl/Literature"</span>, <span class="st">"HGNC/GeneCards"</span>,</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>             <span class="st">"HGNC/Literature"</span>, <span class="st">"Literature/NCBI"</span>, <span class="st">"Literature/GeneCards"</span>),</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">Detectable_in_Dataset =</span> <span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"Yes"</span>, <span class="st">"Yes"</span>, <span class="st">"Yes"</span>, <span class="st">"Yes"</span>, <span class="st">"Yes"</span>)</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sex_age_candidate_genes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Gene_Symbol                  Category
1        XIST Sex Chromosome Expression
2      RPS4Y1 Sex Chromosome Expression
3      EIF1AX X-linked Immune Relevance
4      CD40LG X-linked Immune Relevance
5         B2M     Age-associated Marker
6      S100A8     Age-associated marker
                                                            Relevance  Location
1 Inactivates X chromosome in females; primary biological sex marker.  X-linked
2       Ribosomal protein on Y chromosome; standard male cell marker.  Y-linked
3        X-linked gene escaping inactivation; regulates immune cells.  X-linked
4            Critical for T-B cell interaction and adaptive immunity.  X-linked
5                     Upregulated in older cells due to inflammaging. Autosomal
6     Associated with inflammaging and increased monocyte activation. Autosomal
                Source Detectable_in_Dataset
1   ensembl/Literature                   Yes
2   Ensembl/Literature                   Yes
3       HGNC/GeneCards                   Yes
4      HGNC/Literature                   Yes
5      Literature/NCBI                   Yes
6 Literature/GeneCards                   Yes</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(sex_age_candidate_genes, <span class="at">file =</span> <span class="st">"sex_age_candidate_genes.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pbmc_filtered<span class="sc">@</span>meta.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                      orig.ident nCount_RNA nFeature_RNA percent.mt  donor
D1_AAACCCTGTGACGAGT-1     Donor1       4890         2102   3.619632 Donor1
D1_AAACGAATCAGGCTAC-1     Donor1      12498         3564   3.768603 Donor1
D1_AAACGATGTCTTGAAC-1     Donor1      10305         2945   3.114993 Donor1
D1_AAACGATGTTAGCCCA-1     Donor1       5975         2422   4.033473 Donor1
D1_AAACGCCTCATGTCTC-1     Donor1      10354         2989   1.603245 Donor1
D1_AAACGGACATGATCCC-1     Donor1      12952         3689   4.663372 Donor1
                         sex age_group RNA_snn_res.0.5 seurat_clusters
D1_AAACCCTGTGACGAGT-1 Female     Adult               6               6
D1_AAACGAATCAGGCTAC-1 Female     Adult               0               1
D1_AAACGATGTCTTGAAC-1 Female     Adult               0               1
D1_AAACGATGTTAGCCCA-1 Female     Adult               6               6
D1_AAACGCCTCATGTCTC-1 Female     Adult               0               1
D1_AAACGGACATGATCCC-1 Female     Adult               3               7
                             celltype RNA_snn_res.0.2 RNA_snn_res.0.4
D1_AAACCCTGTGACGAGT-1 CD14+ Monocytes               0               6
D1_AAACGAATCAGGCTAC-1      CD T cells               0               0
D1_AAACGATGTCTTGAAC-1      CD T cells               0               0
D1_AAACGATGTTAGCCCA-1 CD14+ Monocytes               0               6
D1_AAACGCCTCATGTCTC-1      CD T cells               0               0
D1_AAACGGACATGATCCC-1 CD14+ Monocytes               2               2
                      RNA_snn_res.0.6 RNA_snn_res.0.8
D1_AAACCCTGTGACGAGT-1               6               6
D1_AAACGAATCAGGCTAC-1               1               1
D1_AAACGATGTCTTGAAC-1               1               1
D1_AAACGATGTTAGCCCA-1               6               6
D1_AAACGCCTCATGTCTC-1               1               1
D1_AAACGGACATGATCCC-1               4               7</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(pbmc_filtered<span class="sc">@</span>meta.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "percent.mt"     
 [5] "donor"           "sex"             "age_group"       "RNA_snn_res.0.5"
 [9] "seurat_clusters" "celltype"        "RNA_snn_res.0.2" "RNA_snn_res.0.4"
[13] "RNA_snn_res.0.6" "RNA_snn_res.0.8"</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>cell_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(pbmc_filtered<span class="sc">$</span>donor, <span class="fu">Idents</span>(pbmc_filtered))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>cell_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        
         CD T cells CD4 T cells CD14+ Monocytes B cells NK cells
  Donor1        737        1584            1337     164      338
  Donor2        286        1715             920     435      434
  Donor3        557        1300            1525     128      153
  Donor4        436         954            1186     545      218</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a> <span class="co">#| cache: true</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">file.exists</span>(<span class="st">"sex_de_results.rds"</span>)) {</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  sex_de_results <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="fu">getwd</span>(), <span class="st">"sex_de_results.rds"</span>))</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  cell_types <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">Idents</span>(pbmc_filtered))</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  sex_de_results <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (ct <span class="cf">in</span> cell_types) {</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>    sub_obj <span class="ot">&lt;-</span> <span class="fu">subset</span>(pbmc_filtered, <span class="at">idents =</span> ct)</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>    markers <span class="ot">&lt;-</span> <span class="fu">FindMarkers</span>(sub_obj, <span class="at">ident.1 =</span> <span class="st">"Male"</span>, <span class="at">ident.2 =</span> <span class="st">"Female"</span>, <span class="at">group.by =</span> <span class="st">"sex"</span>, <span class="at">pseudobulk =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>    sex_de_results[[ct]] <span class="ot">&lt;-</span> markers</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">saveRDS</span>(sex_de_results, <span class="fu">file.path</span>(<span class="fu">getwd</span>(), <span class="st">"sex_de_results.rds"</span>))</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sex_de_results[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       p_val avg_log2FC pct.1 pct.2 p_val_adj
XIST       0  14.199096 0.904 0.000         0
UTY        0 -13.557819 0.000 0.845         0
RPS4Y1     0 -13.290861 0.000 0.805         0
DDX3Y      0 -13.008651 0.000 0.802         0
USP9Y      0  -9.260938 0.002 0.509         0
KDM5D      0 -11.201458 0.000 0.406         0</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a> <span class="co">#| cache: true</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>sex_chrom_genes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"XIST"</span>, <span class="st">"RPS4Y1"</span>, <span class="st">"KDM5D"</span>, <span class="st">"UTY"</span>, <span class="st">"ZFY"</span>, <span class="st">"DDX3Y"</span>, <span class="st">"EIF1AY"</span>, <span class="st">"KDM5C"</span>,<span class="st">"TSIX"</span>, <span class="st">"RPS4X"</span>, <span class="st">"EIF1AX"</span>, <span class="st">"USP9Y"</span>, <span class="st">"TXLNGY"</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>filtered_sex_results <span class="ot">&lt;-</span> <span class="fu">lapply</span>(sex_de_results, <span class="cf">function</span>(df) {</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  df_filtered <span class="ot">&lt;-</span> df[<span class="sc">!</span><span class="fu">rownames</span>(df) <span class="sc">%in%</span> sex_chrom_genes, ]</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  df_filtered <span class="ot">&lt;-</span> df_filtered[<span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"^MT-"</span>, <span class="fu">rownames</span>(df_filtered)), ]</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>  df_sig <span class="ot">&lt;-</span> df_filtered[df_filtered<span class="sc">$</span>p_val_adj <span class="sc">&lt;</span> <span class="fl">0.05</span>, ]</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df_sig)</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(filtered_sex_results, head)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$`CD14+ Monocytes`
                        p_val  avg_log2FC pct.1 pct.2     p_val_adj
LINC00278        0.000000e+00 -11.2622428 0.000 0.328  0.000000e+00
HLA-C           1.487021e-288  -0.9596481 0.905 0.952 4.072207e-284
MALAT1          6.237660e-262   0.3994571 0.997 0.998 1.708183e-257
ENSG00000290574 1.479018e-246  -2.6015028 0.063 0.367 4.050291e-242
CYBA            3.504248e-209  -1.0308351 0.741 0.852 9.596384e-205
ENSG00000289826 2.693328e-193 -10.3767168 0.000 0.192 7.375679e-189

$`CD T cells`
                        p_val avg_log2FC pct.1 pct.2     p_val_adj
SLC35F1          0.000000e+00 -6.3475699 0.018 0.615  0.000000e+00
ATP8A1           0.000000e+00 -2.4165900 0.377 0.899  0.000000e+00
SNHG5           3.360271e-132  0.7816327 0.965 0.879 9.202102e-128
ENSG00000289826 1.226805e-121 -9.2212455 0.000 0.227 3.359605e-117
FMN1            6.228518e-121  1.7384615 0.533 0.154 1.705680e-116
DDX3X           2.701849e-109  0.8276504 0.951 0.864 7.399014e-105

$`CD4 T cells`
                   p_val avg_log2FC pct.1 pct.2     p_val_adj
SLC35F1     0.000000e+00  -4.797220 0.031 0.403  0.000000e+00
LINC00278  1.689273e-286 -11.454857 0.000 0.291 4.626073e-282
HLA-DRB6   9.415075e-245   2.401369 0.470 0.178 2.578318e-240
HLA-DQA2   2.697225e-195   3.249419 0.229 0.028 7.386351e-191
TTTY14     1.019688e-175  -8.009014 0.002 0.192 2.792415e-171
ANKRD36BP2 1.218498e-130   3.383072 0.170 0.026 3.336855e-126

$`B cells`
                 p_val avg_log2FC pct.1 pct.2   p_val_adj
FYB1      2.493247e-07   2.721523 0.674 0.206 0.006827756
LINC02899 1.054299e-06   4.980988 0.419 0.048 0.028871990
DISC1     1.338176e-06   2.092203 0.651 0.222 0.036645945</code></pre>
</div>
</div>
<p># Exploratory Sex-Associated Gene Expression Analysis in PBMC</p>
<p>## 1. Introduction and Quality Control</p>
<p>In this analysis, we investigated sex-associated gene expression patterns across different PBMC cell types using a pseudobulk methodology. To account for biological replication properly and avoid psudoreplication errors, individual donors ($n=4$; 2 male, 2 female) were treated as the biological unit of analysis.</p>
<p>Cell counts and distributions across donors were validated to ensure balanced representation:</p>
<p>-**<strong>XIST Expression</strong>**: Strongly upregulated in female donors across major cell types ($avg/_log2FC/approx +14.2$, <span class="math inline">\(p_{adj} = 0\)</span>).</p>
<p>-**<strong>Y-Chromosome Markers</strong>**: Highly significant expression of Y-linked genes (“UTY”, “RPS4Y1”, “DDX3Y”, “KDM5D”, “USP9Y”, “TXLNGY”) exclusively in male donors ($avg/_log2FC/approx -9$ to <span class="math inline">\(-13\)</span>, <span class="math inline">\(p_{adj} = 0\)</span>).</p>
<p>## 2. Autosomal Gene Expression Analysis (Post-Filtering)</p>
<p>To isolate potential immune-related autosomal gene expression differences independent of direct sex-chromosome dosage, we filtered out all known sex-chromosome genes and mitochondrial transcripts (“MT-” genes) to eliminate technical or metabolic variance.</p>
<p>Following this rigorous filtering:</p>
<p>-No widespread or statistically robust differential expression patterns remained across autosomal genes.</p>
<p>-Only a minimal subset of genes (“FYB1”, “LINC02899”, “DISC1”) showed marginal significance ($p_{adj}&lt;0.05$).</p>
<p>## 3. Discussion and Limitations</p>
<p>The primary finding confirms thatpsudobulk differential expression successfully captures core sex-linked signatures (“XIST” and Y-chromosomal genes). However, the absence of widespread autosomal differences highlights key experimental constraints:</p>
<p>1.**<strong>Sample Size:</strong>** The dataset comprises a limited cohort of 4 donors, constraining statistical power.</p>
<p>2.**<strong>Confounding Variables:</strong>** Donor age, batch effects, and individual inter-donor variability are confounded with biological sex in this specific cohort.</p>
<p>Therefore, observed minor autosomal variations likely reflect individual donor heterogeneity rather than a broad, systemic sex-specific imune profile.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>meta_data <span class="ot">&lt;-</span> pbmc_filtered<span class="sc">@</span>meta.data</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>prop_df <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(meta_data<span class="sc">$</span>donor, meta_data<span class="sc">$</span>celltype), <span class="at">margin =</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>prop_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(prop_df)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(prop_df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Donor"</span>, <span class="st">"CellType"</span>, <span class="st">"Proportion"</span>)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>donor_sex <span class="ot">&lt;-</span> <span class="fu">unique</span>(meta_data[, <span class="fu">c</span>(<span class="st">"donor"</span>, <span class="st">"sex"</span>)])</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>prop_df <span class="ot">&lt;-</span> <span class="fu">merge</span>(prop_df, donor_sex, <span class="at">by.x =</span> <span class="st">"Donor"</span>, <span class="at">by.y =</span> <span class="st">"donor"</span>)</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(prop_df, <span class="fu">aes</span>(<span class="at">x =</span> CellType, <span class="at">y =</span> Proportion, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitterdodge</span>(), <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">60</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Comparison of Cell Type Proportions by Sex"</span>,</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Cell Type"</span>, <span class="at">y =</span> <span class="st">"Proportion (%)"</span>, <span class="at">fill =</span> <span class="st">"sex"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<pre><code></code></pre>
<pre><code></code></pre>
<pre><code></code></pre>
<pre><code></code></pre>
<pre><code></code></pre>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>